### PR TITLE
LISIRD notebook

### PR DESCRIPTION
**Pull request by sapols**
This PR adds a Jupyter notebook showing how to interact with LISIRD data, just like the one we have for SWP.

It has all the same types of examples except it uses LISIRD datasets instead of SWP ones. The biggest difference is the last example. At the end of the SWP notebook, we had an example showing how to display images from image URL datasets. In this notebook, I instead show how to visualize SSI datasets with a heatmap.

### CODE REVIEW

**Comment by sapols** [comment]
Note that the diff won't render the notebook here, but GitHub will render it if you go back and access it from the main repo.

**Review by hleise — APPROVED** [review]

**Comment by hleise** [comment]
Looks good! The only thing that I'm not entirely sure about is the use of "LASP's Interactive Solar Irradiance Data Center". Since it's technically a product name, should we be strict about always calling it the "LASP Interactive Solar Irradiance Data Center" rather than "LASP's" in this case?

**Comment by sapols** [comment]
Thanks for catching that, @hleise. I updated the notebook to make it say "the LASP Interactive..." instead of "LASP's..."

**Comment by lindholc** [comment]
Should there be units for wavelength and irradiance in the SSI plot at the end?

**Comment by sapols** [comment]
@lindholc Good suggestion. It was trivial to add the units to the axis labels so I added them.

**Review by lindholc — APPROVED** [review]

**Review by dlindhol — APPROVED** [review]

**Pull request merged**
